### ISSUE TITLE
dap.continue() using default Python configuration seems to do nothing

### ISSUE THREAD

**Issue by wbthomason** [mfussenegger/nvim-dap#25]
Thanks for what looks to be a promising plugin/hopefully an addition to core, eventually!

I've been trying to use the configuration for Python given in the docs to test this out, but unfortunately, I can't seem to start a debug session. I suspect I'm missing something about how to use this.

Specifically, with the following configuration:
```lua
local dap = require('dap')
local function get_python()
    local python_path = '/usr/bin/python'
    local virtualenv = vim.fn.getenv('VIRTUAL_ENV')
    if virtualenv ~= vim.NIL and virtualenv ~= '' then
        python_path = virtualenv .. '/bin/python'
    end

    return python_path
end

dap.adapters.python = {
    type = 'executable',
    command = get_python(),
    args = {'-m', 'debugpy.adapter'}
}

dap.configurations.python = {
    {
        type = 'python',
        request = 'launch',
        name = "Launch file",
        program = "${file}",
        pythonPath = get_python()
    }
}
```
running `:lua require'dap'.continue()` in a Python buffer doesn't seem to do anything - I neither get errors nor any indication of a debug session starting.

I've checked that running the command I specify manually - that is, running `/path/to/bin/python -m debugpy.adapter` - correctly starts `debugpy`, so I _think_ I have the adapter installed correctly.

Am I missing something? Is this the correct way to use `nvim-dap`? Is there some way I can view debug logs, etc.?

Thanks!

**Comment by mfussenegger** [comment]
Did you set any breakpoints, or opened the repl to see if there is any output?

There is a logfile in `:lua print(vim.fn.stdpath('data'))`  called `vim-dap.log`. 
You can change the log level with `:lua require('dap').set_log_level('trace')` (though if there is an error, the default level should already work) 

Unfortunately for python the `console = 'integratedTerminal';`, option doesn't work unless you've the patch in https://github.com/neovim/neovim/pull/11839 applied.
So with the configuration there is right now you won't get any feedback about the process being launched. Any "console output" is currently being redirected to the REPL.

**Comment by wbthomason** [comment]
> Did you set any breakpoints, or opened the repl to see if there is any output?

I haven't tried setting any breakpoints yet, but I have tried opening the REPL. I get a similar lack of response (I also thought that calling `continue()` would open the REPL for me?)

> There is a logfile in :lua print(vim.fn.stdpath('data')) called vim-dap.log.

Ah, great, thanks! By setting the log level to trace, I can see I'm getting a `FileNotFoundError` from `debugpy`. It looks like there's a duplicated directory in the path it's trying to run (e.g. the file is at `/path/to/dir/file.py` and the `FileNotFoundError` is saying (correctly) that `/path/to/dir/dir/file` does not exist). This only happens when I'm in a virtualenv (using `poetry`), so it's likely an issue specific to paths in that context, and seems like a problem with my config rather than with `nvim-dap`.

> Unfortunately for python the console = 'integratedTerminal';, option doesn't work unless you've the patch in neovim/neovim#11839 applied.
So with the configuration there is right now you won't get any feedback about the process being launched. Any "console output" is currently being redirected to the REPL.

I see. I didn't know that, and (though I'm using `neovim` from `master`) I do not have that patch applied. I had expected that just opening the REPL would allow me to set breakpoints before running, as with e.g. `gdb` or `lldb`; if this isn't the case, then (combined with the bug mentioned in the linked patch), that would explain the total lack of output.

Given all this, I'll close the issue for now, see if I can fix the aforementioned path error, and wait for the patch to be merged. Thank you!

**Comment by mfussenegger** [comment]
> By setting the log level to trace, I can see I'm getting a FileNotFoundError from debugpy.

Could you share the exact log message?
I guess it would make sense to print the message out so that there isn't a total lack of feedback.

**Comment by wbthomason** [comment]
Here's the full log:
<details>

```
[ DEBUG ] 2020-06-26T13:12:30Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:658 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ DEBUG ] 2020-06-26T13:12:30Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "telemetry",
    data = {
      packageVersion = "1.0.0b11"
    },
    output = "ptvsd"
  },
  event = "output",
  seq = 1,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:30Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "telemetry",
    data = {
      packageVersion = "1.0.0b11"
    },
    output = "debugpy"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:30Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    exceptionBreakpointFilters = { {
        default = false,
        filter = "raised",
        label = "Raised Exceptions"
      }, {
        default = true,
        filter = "uncaught",
        label = "Uncaught Exceptions"
      } },
    supportsCompletionsRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsDebuggerProperties = true,
    supportsDelayedStackTraceLoading = true,
    supportsEvaluateForHovers = true,
    supportsExceptionInfoRequest = true,
    supportsExceptionOptions = true,
    supportsGotoTargetsRequest = true,
    supportsHitConditionalBreakpoints = true,
    supportsLogPoints = true,
    supportsModulesRequest = true,
    supportsSetExpression = true,
    supportsSetVariable = true,
    supportsTerminateDebuggee = true,
    supportsValueFormattingOptions = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 3,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-06-26T13:12:30Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:658 ]	"request"	{
  arguments = {
    name = "Launch file",
    program = "flow_generation/regions.py",
    pythonPath = "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/bin/python",
    request = "launch",
    type = "python"
  },
  command = "launch",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  event = "initialized",
  seq = 4,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:658 ]	"request"	{
  command = "configurationDone",
  seq = 5,
  type = "request"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  command = "configurationDone",
  request_seq = 5,
  seq = 5,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  command = "launch",
  request_seq = 4,
  seq = 6,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    isLocalProcess = true,
    name = "flow_generation/regions.py",
    pointerSize = 64,
    startMethod = "launch",
    systemProcessId = 19025
  },
  event = "process",
  seq = 7,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    reason = "started",
    threadId = 1
  },
  event = "thread",
  seq = 8,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "Traceback (most recent call last):\n"
  },
  event = "output",
  seq = 9,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n'
  },
  event = "output",
  seq = 10,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "    return _run_code(code, main_globals, None,\n"
  },
  event = "output",
  seq = 11,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>\n    cli.main()\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 430, in main\n'
  },
  event = "output",
  seq = 12,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '    run()\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 267, in run_file\n'
  },
  event = "output",
  seq = 13,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '    runpy.run_path(options.target, run_name=compat.force_str("__main__"))\n  File "/usr/lib/python3.8/runpy.py", line 264, in run_path\n'
  },
  event = "output",
  seq = 14,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "    "
  },
  event = "output",
  seq = 15,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "code, fname = _get_code_from_file(run_name, path_name)\n"
  },
  event = "output",
  seq = 16,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 234, in _get_code_from_file\n    with io.open_code(decoded_path) as f:\n'
  },
  event = "output",
  seq = 17,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "FileNotFoundError: [Errno 2] No such file or directory: '/home/wil/projects/research/multi-team-warehouse-flow/flow_generation/flow_generation/flow_generation/regions.py'\n"
  },
  event = "output",
  seq = 18,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    reason = "exited",
    threadId = 1
  },
  event = "thread",
  seq = 19,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:32Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    exitCode = 1
  },
  event = "exited",
  seq = 20,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:32Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  event = "terminated",
  seq = 21,
  type = "event"
}
```

</details>

Here's the portion of the log with the error output:
<details>

```
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "Traceback (most recent call last):\n"
  },
  event = "output",
  seq = 9,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n'
  },
  event = "output",
  seq = 10,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "    return _run_code(code, main_globals, None,\n"
  },
  event = "output",
  seq = 11,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>\n    cli.main()\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 430, in main\n'
  },
  event = "output",
  seq = 12,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '    run()\n  File "/home/wil/.cache/pypoetry/virtualenvs/flow-generation-H2ltnddp-py3.8/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 267, in run_file\n'
  },
  event = "output",
  seq = 13,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '    runpy.run_path(options.target, run_name=compat.force_str("__main__"))\n  File "/usr/lib/python3.8/runpy.py", line 264, in run_path\n'
  },
  event = "output",
  seq = 14,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "    "
  },
  event = "output",
  seq = 15,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "code, fname = _get_code_from_file(run_name, path_name)\n"
  },
  event = "output",
  seq = 16,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = '  File "/usr/lib/python3.8/runpy.py", line 234, in _get_code_from_file\n    with io.open_code(decoded_path) as f:\n'
  },
  event = "output",
  seq = 17,
  type = "event"
}
[ DEBUG ] 2020-06-26T13:12:31Z-0400 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:513 ]	{
  body = {
    category = "stderr",
    output = "FileNotFoundError: [Errno 2] No such file or directory: '/home/wil/projects/research/multi-team-warehouse-flow/flow_generation/flow_generation/flow_generation/regions.py'\n"
  },
  event = "output",
  seq = 18,
  type = "event"
}
```
</details>

This is running from `/home/wil/projects/research/multi-team-warehouse-flow/flow_generation/flow_generation/regions.py`; the erroneous path is `/home/wil/projects/research/multi-team-warehouse-flow/flow_generation/flow_generation/flow_generation/regions.py`.
