### ISSUE TITLE
Issues with multiprocessing in python 

### ISSUE THREAD

**Issue by Thieso** [mfussenegger/nvim-dap#362]
### Debug adapter definition and debug configuration

Hello, 
I installed the plugin via vim-plug and I am using it for python. 
I have an application that uses the python multiprocessing library (multithreading in python) and the plugin does not work correctly with it. 

Debug adapter configuration:
```lua
dap.adapters.python = {
  type = 'executable';
  command = 'python';
  args = { '-m', 'debugpy.adapter' };
}

dap.configurations.python = {
    {
        -- The first three options are required by nvim-dap
        type = 'python'; -- the type here established the link to the adapter definition: `dap.adapters.python`
        request = 'launch';
        name = "Launch file";

        -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

        program = "${file}"; -- This configuration will launch the current file if used.
        console = "externalTerminal";
        pythonPath = function()
            -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
            -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
            -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
            local cwd = vim.fn.getcwd()
            if vim.fn.executable(cwd .. '/venv/bin/python') == 1 then
                return cwd .. '/venv/bin/python'
            elseif vim.fn.executable(cwd .. '/.venv/bin/python') == 1 then
                return cwd .. '/.venv/bin/python'
            else
                return '/usr/bin/python'
            end
        end;
    },
}
```

### Debug adapter version

current version (how do I see this number?)

### Steps to Reproduce

1. Create a python file with the content

```python
import multiprocessing as mp


def func():
    try:
        a = 1
    except KeyboardInterrupt:
        print("Interrupted")

parent_con, _ = mp.Pipe()
ps = mp.Process(target=func)
ps.start()
while ps.is_alive():
    ps.join(0)
b = 3
print(b)
```
2. Set a breakpoint at the file `b = 3`
3. Start the debugging process

### Expected Result

The debugger reaches the breakpoint. 

### Actual Result

The debugger never reaches the breakpoint. When the process is killed using CTRL-C the following error gets printed

```
^CTraceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/toeleric/ACIN_Git/testpyright/test.py", line 15, in <module>
    ps.join(0)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 923, in wait
    with _WaitSelector() as selector:
  File "/usr/lib/python3.8/selectors.py", line 348, in __init__
    super().__init__()
  File "/usr/lib/python3.8/selectors.py", line 209, in __init__
    def __init__(self):
  File "_pydevd_bundle/pydevd_cython.pyx", line 1363, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 1664, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_is_thread_alive.py", line 9, in is_thread_alive
    def is_thread_alive(t):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/toeleric/ACIN_Git/testpyright/test.py", line 13, in <module>
    ps.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 913, in new_fork
    _on_forked_process(setup_tracing=apply_arg_patch and not is_subprocess_fork)
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 221, in _on_forked_process
    pydevd.settrace_forked(setup_tracing=setup_tracing)
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3036, in settrace_forked
    settrace(
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2723, in settrace
    _locked_settrace(
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2831, in _locked_settrace
    py_db.wait_for_ready_to_run()
  File "/home/toeleric/ACIN_Git/testpyright/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 799, in wait_for_ready_to_run
    self._py_db_command_thread_event.wait(0.1)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

```

**Comment by Thieso** [comment]
Ok I searched the web a bit further and found a similar issue for vimspector [here](https://github.com/puremourning/vimspector/issues/141). 
Basically the `debugpy` adapter can be told to not go in subprocesses by setting `subProcess` to `false` in the debug config. Then the adapter also does not get stuck. However, I feel like even when set to true, the plugin should not get stuck when no breakpoint is set within a subprocess or is that a undesired?

Anyway, thanks for creating this plugin and I hope this will be helpful to someone.

**Comment by mfussenegger** [comment]
This is because `debugpy` requires an out-of-spec extension to support debugging of multiprocessing. See https://github.com/mfussenegger/nvim-dap-python/issues/20 & https://github.com/mfussenegger/nvim-dap-python/pull/21
