### ISSUE TITLE
ChromeDebug ECONNREFUSEd

### ISSUE THREAD

**Issue by EpsilonKu** [mfussenegger/nvim-dap#452]
### Debug adapter definition and debug configuration

```lua 
dap.adapters.chrome = {
    type = "executable",
    command = "node",
    args = {os.getenv("HOME") .. "/.local/bin/vscode-chrome-debug/out/src/chromeDebug.js"} 
}

dap.configurations.vue = {
    {
        type = "chrome",
        request = "attach",
        program = "${file}",
        cwd = vim.fn.getcwd(),
        sourceMaps = true,
        protocol = "inspector",
        port = 9222,
        webRoot = "${workspaceFolder}"
    },
  }

```

### Steps to Reproduce

1. Opened Vue template project.
2. Started `:lua require'dap'.continue()`

### Expected Result

Clean debug

### Actual Result

```

[ DEBUG ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:851 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ DEBUG ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:561 ]	{
  body = {
    exceptionBreakpointFilters = { {
        default = false,
        filter = "all",
        label = "All Exceptions"
      }, {
        default = false,
        filter = "uncaught",
        label = "Uncaught Exceptions"
      } },
    supportsBreakpointLocationsRequest = true,
    supportsCompletionsRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsDelayedStackTraceLoading = true,
    supportsEvaluateForHovers = true,
    supportsExceptionInfoRequest = true,
    supportsHitConditionalBreakpoints = true,
    supportsLoadedSourcesRequest = true,
    supportsLogPoints = true,
    supportsRestartFrame = true,
    supportsRestartRequest = true,
    supportsSetExpression = true,
    supportsSetVariable = true,
    supportsValueFormattingOptions = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 1,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:851 ]	"request"	{
  arguments = {
    cwd = "/home/epsku/Projects/vue-hello/my-project",
    port = 9222,
    program = "/home/epsku/Projects/vue-hello/my-project/src/components/HelloWorld.vue",
    protocol = "inspector",
    request = "attach",
    sourceMaps = true,
    type = "chrome",
    webRoot = "/home/epsku/Projects/vue-hello/my-project"
  },
  command = "attach",
  seq = 1,
  type = "request"
}
[ DEBUG ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:561 ]	{
  body = {
    category = "telemetry",
    data = {
      ["Versions.DebugAdapter"] = "4.13.0",
      ["Versions.DebugAdapterCore"] = "6.8.9",
      requestType = "request",
      successful = "true",
      timeTakenInMilliseconds = "1.353704"
    },
    output = "ClientRequest/initialize"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ INFO ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:396 ]	"Telemetry"	"ClientRequest/initialize"
[ DEBUG ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:561 ]	{
  body = {
    category = "telemetry",
    data = {
      ["Versions.DebugAdapter"] = "4.13.0",
      ["Versions.DebugAdapterCore"] = "6.8.9",
      args = { "cwd", "port", "webRoot", "type", "program", "request", "sourceMaps", "protocol", "pathMapping", "sourceMapPathOverrides", "skipFileRegExps", "targetFilter", "smartStep", "showAsyncStacks" },
      request = "attach"
    },
    output = "debugStarted"
  },
  event = "output",
  seq = 3,
  type = "event"
}
[ INFO ] 2022-02-27T15:23:54Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:396 ]	"Telemetry"	"debugStarted"
[ DEBUG ] 2022-02-27T15:24:04Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:561 ]	{
  body = {
    category = "telemetry",
    data = {
      ["!exceptionId"] = "2010",
      ["!exceptionMessage"] = "Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).",
      ["!exceptionStack"] = "Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).\n    at Object.runtimeConnectionTimeout (/home/epsku/.local/bin/vscode-chrome-debug/node_modules/vscode-chrome-debug-core/out/src/errors.js:91:12)\n    at /home/epsku/.local/bin/vscode-chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeConnection.js:110:49\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      ["Versions.DebugAdapter"] = "4.13.0",
      ["Versions.DebugAdapterCore"] = "6.8.9",
      exceptionName = "Error",
      exceptionType = "firstChance",
      requestType = "request",
      successful = "false",
      timeTakenInMilliseconds = "9959.098319"
    },
    output = "ClientRequest/attach"
  },
  event = "output",
  seq = 4,
  type = "event"
}
[ INFO ] 2022-02-27T15:24:04Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:396 ]	"Telemetry"	"ClientRequest/attach"
[ DEBUG ] 2022-02-27T15:24:04Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:561 ]	{
  body = {
    error = {
      format = "Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).",
      id = 2010,
      variables = {
        _error = "Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222",
        _timeout = "10000"
      }
    }
  },
  command = "attach",
  message = "Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).",
  request_seq = 1,
  seq = 5,
  success = false,
  type = "response"
}
[ INFO ] 2022-02-27T15:24:04Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:730 ]	"Closed all handles"
[ INFO ] 2022-02-27T15:24:04Z+0600 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:733 ]	"Process closed"	175615	false

```

**Comment by mfussenegger** [comment]
Did you see this part?

> note: chrome has to be started with a remote debugging port google-chrome-stable --remote-debugging-port=9222

**Comment by EpsilonKu** [comment]
Ok, so I run `npm run dev` and ` google-chrome-stable --remote-debugging-port=9222`. It run well, but when It should stop on breakpoint, #449 happened. I will close this issue because it don't related to this.
