### ISSUE TITLE
macOS M1, delve: error layer=dap recovered panic: reflect: reflect.Value.Set using value obtained using unexported field

### ISSUE THREAD

**Issue by nyngwang** [mfussenegger/nvim-dap#944]
### Debug adapter definition and debug configuration

I got the following error when typing `dlv config` in dap-repl.

```
[debug-adapter stderr] 2023-05-08T10:24:48+08:00 error layer=dap recovered panic: reflect: reflect.Value.Set using value obtained using unexported field
goroutine 20 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/go-delve/delve/service/dap.(*Session).recoverPanic(0x140002322d0, {0x103500a60, 0x140003acd20})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:555 +0x44
panic({0x103437da0, 0x140003979d0})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:890 +0x258
reflect.flag.mustBeAssignableSlow(0x0?)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/reflect/value.go:259 +0xb4
reflect.flag.mustBeAssignable(...)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/reflect/value.go:249
reflect.Value.Set({0x103431aa0?, 0x140002322f0?, 0x1?}, {0x103431aa0?, 0x1400061f720?, 0x1032b8234?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/reflect/value.go:2230 +0x54
github.com/go-delve/delve/pkg/config.ConfigureSetSimple({0x0, 0x0}, {0x0, 0x0}, {0x103431aa0?, 0x140002322f0?, 0x0?})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/pkg/config/split.go:125 +0x180
github.com/go-delve/delve/service/dap.configureSet(0x0?, {0x0?, 0x140009c7278?})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/config.go:39 +0x170
github.com/go-delve/delve/service/dap.(*Session).evaluateConfig(0x140002322d0, 0x2?, 0x6?, {0x0, 0x0})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/command.go:123 +0xf8
github.com/go-delve/delve/service/dap.(*Session).delveCmd(0x140002322d0, 0xa?, 0x103310e68?, {0x1400061f710?, 0x0?})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/command.go:24 +0x2e8
github.com/go-delve/delve/service/dap.(*Session).onEvaluateRequest(0x140002322d0, 0x140003acd20)
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:2635 +0x8a4
github.com/go-delve/delve/service/dap.(*Session).handleRequest(0x140002322d0, {0x103500a60?, 0x140003acd20?})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:739 +0xf64
github.com/go-delve/delve/service/dap.(*Session).ServeDAPCodec(0x140002322d0)
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:541 +0x308
github.com/go-delve/delve/service/dap.(*Server).runSession(0x1400027cc90, {0x12ae5a698?, 0x140001945e8?})
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:478 +0x148
github.com/go-delve/delve/service/dap.(*Server).Run.func1()
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:470 +0xa4
created by github.com/go-delve/delve/service/dap.(*Server).Run
	/Users/ningwang/go/pkg/mod/github.com/go-delve/delve@v1.20.2/service/dap/server.go:452 +0x68



Internal Error
```

### Debug adapter version

1.20.2

### Steps to Reproduce

1. Create a hello world project in Go.

```go
// create a simple hello world program.
package main

import "fmt"

func main() {
  fmt.Println("Hello, World!") -- I set breakpoint this line.
}
```

2. Use these config:

```lua
  dap.adapters.go = {
    type = 'server',
    port = '${port}',
    executable = {
      command = vim.fn.stdpath('data') .. '/mason/packages/delve/dlv',
      args = { 'dap', '-l', '127.0.0.1:${port}' },
    },
  }

  dap.configurations.go = {
    {
      name = 'Debug',
      type = 'go',
      request = 'launch', -- 'launch' or 'attach' to program.
      program = '${file}', -- run for the current buffer.
      -- showLog = false,
      -- dlvToolPath = vim.fn.exepath('dlv'),
    },
    {
      name = "Debug test (go.mod)",
      type = "go",
      request = "launch",
      mode = "test",
      program = "./${relativeFileDirname}",
    },
    {
      name = "Attach (Pick Process)",
      type = "go",
      mode = "local",
      request = "attach",
      processId = require('dap.utils').pick_process,
    },
    {
      name = "Attach (127.0.0.1:9080)",
      type = "go",
      mode = "remote",
      request = "attach",
      port = "9080"
    },
  }
```

3. Set a single breakpoint at any line of it and run `dap.continue()`, and then select the first configuration above, i.e. `name = "Debug"`
4. After the dap-repl window appeared, type the command in it `dlv config`.

### Expected Result

No error.

### Actual Result

reflect.Value.Set using value obtained using unexported field

https://user-images.githubusercontent.com/24765272/236722442-eddd73f0-b676-413a-bcf0-b440da373e04.mov

**Comment by nyngwang** [comment]
Hi, sorry for the report, I just realized it's not a problem of nvim-dap. Closing.
